function [D]=design_phastimate_filter (ord, freq, fs)
    if ~isempty(ord)
        D=designfilt('bandpassfir', 'FilterOrder', ord, 'CutoffFrequency1',...
                freq(1), 'CutoffFrequency2', freq(2), 'SampleRate', fs, 'DesignMethod', 'window');
    else

        D = designfilt('bandpassfir', 'StopbandFrequency1', freq(1)-1.5, ...
                       'PassbandFrequency1', freq(1), 'PassbandFrequency2', ...
                       freq(2), 'StopbandFrequency2', freq(2)+1.5, ...
                       'StopbandAttenuation1', 20, 'PassbandRipple', 1, ...
                       'StopbandAttenuation2', 20, 'SampleRate', fs*1, ...
                       'DesignMethod', 'equiripple');
    end
end